url: https://jgoodall.me

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  input: GFM

future: false
paginate: 5
paginate_path: "/posts/page:num/"

title: John Goodall
description: John Goodall is Research Scientist at Oak Ridge National Laboratory.
author: johnrgoodall
email: jgoodall@ornl.gov
phone: 865-446-0611

# For use with [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag)
social:
  type: person
  name: John R. Goodall
  links:
    - https://twitter.com/johnrgoodall
    - https://www.linkedin.com/in/johnrgoodall
    - https://github.com/jgoodall

employer: Oak Ridge National Laboratory
employer_url: https://www.ornl.gov/
group: Cyber and Information Security Research group
group_url: http://www.csiir.ornl.gov/
team: Situation Awareness and Visual Analytics team

twitter:
  username: johnrgoodall
linkedin:
  username: johnrgoodall
github:
  username: jgoodall

cv_url: https://www.dropbox.com/s/sgxga9hr5rs6o9i/goodall_cv.pdf?dl=0
